name: Bug Report
description: Report broken links, outdated info, or errors
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the roadmap!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What issue did you find?
      placeholder: Describe the problem...
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the issue?
      placeholder: |
        - Section: iOS Fundamentals
        - Topic: SwiftUI
        - Resource: [name of resource]
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      options:
        - Broken Link
        - Outdated Information
        - Incorrect Content
        - Missing Topic
        - Typo
        - Other
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: How should this be corrected?
      placeholder: Replace with...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: I have verified the issue
          required: true
