name: 🐛 Bug Report
description: Report a broken link, incorrect information, or formatting issue
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue!

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of issue is this?
      options:
        - Broken link
        - Incorrect information
        - Formatting issue
        - Outdated content
        - Typo
        - Other
    validations:
      required: true

  - type: input
    id: file
    attributes:
      label: File/Section
      description: Which file or section has the issue?
      placeholder: "e.g., README.md, roadmaps/ios-roadmap.md"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue in detail
      placeholder: "The link to XYZ returns a 404..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected
      description: What should it be instead?
      placeholder: "The correct URL is..."
    validations:
      required: false
