name: ✨ Feature Request
description: Suggest a new resource, section, or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! We appreciate community input.

  - type: dropdown
    id: type
    attributes:
      label: Request Type
      description: What kind of addition or change?
      options:
        - New resource/link
        - New roadmap section
        - New project idea
        - Improve existing content
        - New platform/framework track
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your suggestion in detail
      placeholder: "I think we should add a section about..."
    validations:
      required: true

  - type: textarea
    id: value
    attributes:
      label: Why is this valuable?
      description: How would this help mobile developers?
      placeholder: "This would help developers who..."
    validations:
      required: true

  - type: textarea
    id: resources
    attributes:
      label: Relevant Links
      description: Any links or references to support your suggestion?
      placeholder: "https://..."
    validations:
      required: false
