name: Feature Request
description: Suggest new topics, paths, or resources
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have something to add? We'd love to hear!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added?
      placeholder: Describe your suggestion...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New Learning Path
        - New Topic
        - Resource Recommendation
        - Structure Improvement
        - Visual/Diagram
        - Other
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - iOS
        - Android
        - Cross-Platform
        - General
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why should this be included?
      placeholder: This is important because...
    validations:
      required: true

  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: Any specific resources to include?
      placeholder: |
        - https://example.com
        - Book: "Title"
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I can help add this content
          required: false
